targetNamespace: ''
parameters: {}
packages:
  - name: geocoding
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: geocoding
        binary: false
        main: ''
        runtime: 'python:default'
        web: true
        parameters: {}
        environment: {GOOGLE_GEOCODING_API_KEY: "${GOOGLE_GEOCODING_API_KEY}",
                      REDIS_CONNECTION_STRING: "${REDIS_CONNECTION_STRING}"}
        annotations: {}
        limits: {}
